// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csyadwpfvikhljogojtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzeWFkd3BmdmlraGxqb2dvanRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzI2NjksImV4cCI6MjA2NzA0ODY2OX0.P4l6LE60ERhH9vgXS5IJWrT33m5WS-Q9jOa23k58tFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});